require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
