inherit_from: 
  - .rubocop.ruby.yml
  - .rubocop.rspec.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false 